# Site settings
title: 꾸리블로그
email: rudals4549l@naver.com
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: 배움은 의무도, 생존도 아니다.

# Social icons
facebook: 
likedin:
github: kookyungmin
deviantart: 
codepen: 

footer: © Taken theme

# Build settings
markdown: kramdown
